<?php

use \Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Url;
use \Drupal\Core\Asset\AttachedAssetsInterface;

function gin_login_page_attachments_alter(&$page) {
  // Get path
  $route = \Drupal::routeMatch()->getRouteName();

  // Chek if path is available and we're at user level
  if (
    $route == 'user.login' ||
    $route == 'user.pass' ||
    $route == 'user.register'
  ) {
    $page['#attached']['library'][] = 'gin_login/gin_login';
  }
}

/**
 ** Page title alter()
 **/
function gin_login_theme_suggestions_page_title_alter(array &$suggestions, array $variables) {
  // Are we looking at a user?
  $route = \Drupal::routeMatch()->getRouteName();

  // Chek if path is available and we're at user level
  if (
    $route == 'user.login' ||
    $route == 'user.pass' ||
    $route == 'user.register'
  ) {
    $path = str_replace('.', '_', $route);

    $suggestions[] = 'page_title__user';
    $suggestions[] = 'page_title__' . $path;
  }
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function gin_login_form_alter(&$form, $form_state, $form_id) {
  // User form (Login, Register or Forgot password)
  if (strpos($form_id, 'user_login') !== false || strpos($form_id, 'user_register') !== false || strpos($form_id, 'user_pass') !== false) {
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
  }

  // Adding button/links to Register and Forgot password
  if (strpos($form_id, 'user_login') !== false) {
    // Move actions before new elements
    $form['actions']['#weight'] = '98';

    // Add new class to submit button
    $form['actions']['submit']['#attributes']['class'][] = 'button-login';

    // New wrapper
    $form['more-links'] = array(
      '#type' => 'container',
      '#weight' => '99',
      '#attributes' => ['class'=>['more-links']],
    );

    // Register button
    $form['more-links']['register_button'] = array(
      '#type' => 'link',
      '#url' => Url::fromRoute('user.register'),
      '#title' => t('Create new account'),
      '#attributes' => ['class'=>['register-button', 'button', 'button--secondary']],
      '#weight' => '1'
    );

    // Forgot password link
    $form['more-links']['forgot_password_link'] = array(
      '#type' => 'link',
      '#url' => Url::fromRoute('user.pass'),
      '#title' => t('Forgot your password?'),
      '#attributes' => ['class'=>['link', 'forgot-password-link']],
      '#weight' => '2'
    );
  }

  // Changing name of Reset button
  if (strpos($form_id, 'user_pass') !== false) {
    $form['actions']['submit']['#value'] = t('Reset');
  }
 }

/**
 ** Theme()
 **/
function gin_login_theme() {
  // Page
  $theme['page__user__login'] = [
    'template' => 'page/page--user--login',
  ];
  $theme['page__user__password'] = [
    'template' => 'page/page--user--password',
  ];
  $theme['page__user__register'] = [
    'template' => 'page/page--user--register',
  ];

  // Title
  $theme['page_title__user_login'] = [
    'template' => 'content/page-title--user-login',
  ];
  $theme['page_title__user_pass'] = [
    'template' => 'content/page-title--user-pass',
  ];
  $theme['page_title__user_register'] = [
    'template' => 'content/page-title--user-register',
  ];

  return $theme;
}

/**
 ** CSS()
 **/
function gin_login_css_alter(&$css, $assets) {
  // UPDATE THIS PATH TO YOUR MODULE'S CSS PATH
  $path = drupal_get_path('module', 'gin_login') . '/dist/css/gin_login.css';
  if (isset($css[$path])) {
    // Use anything greater than 100 to have it load after the theme as CSS_AGGREGATE_THEME is set to 100.
    $css[$path]['group'] = 200;
  }
}
