<?php

/**
 * @file
 * gin_login.module
 */

use Drupal\Core\Url;
use Drupal\Core\Render\Markup;
use Drupal\user\UserInterface;

/**
 * Page_attachments_alter()
 */
function gin_login_page_attachments_alter(&$page) {
  // Get path.
  $route = \Drupal::routeMatch()->getRouteName();

  // Is User logged in?
  $logged_in = \Drupal::currentUser()->isAuthenticated();

  // Is Gin the default admin theme?
  $admin_theme = \Drupal::config('system.theme')->get('admin');

  if ($admin_theme === 'gin') {
    // Get user config accent color.
    $config = \Drupal::config('gin.settings');
    $accent_color = $config->get('accent_color');

    if ($accent_color) {
      $accent_color_hover = _gin_login_adjust_brightness($accent_color, -0.1);
      $accent_color_active = _gin_login_adjust_brightness($accent_color, -0.2);
      $accent_color_a20 = _gin_login_adjust_brightness($accent_color, 0.92);
      $accent_color_svg = str_replace('#', '%23', $accent_color);

      $accent_color_css = <<<EOH
        :root {
          --colorPrimary: $accent_color !important;
          --colorPrimaryHover: $accent_color_hover !important;
          --colorPrimaryActive: $accent_color_active !important;
        }
      EOH;

      if (
        $logged_in ||
        $route == 'user.login' ||
        $route == 'user.pass' ||
        $route == 'user.register'
      ) {
        $page['#attached']['html_head'][] = [
          [
            '#tag' => 'style',
            '#value' => Markup::create($accent_color_css),
          ],
          'gin-accent-color',
        ];
      }
    }
  }

  // Check if path is available and we're at user level.
  if (
    $route == 'user.login' ||
    $route == 'user.pass' ||
    $route == 'user.register'
  ) {
    $page['#attached']['library'][] = 'gin_login/gin_login';
  }
}

/**
 * Page title alter()
 */
function gin_login_theme_suggestions_page_title_alter(array &$suggestions, array $variables) {
  // Get path.
  $route = \Drupal::routeMatch()->getRouteName();

  // Chek if path is available and we're at user level.
  if (
    $route == 'user.login' ||
    $route == 'user.pass' ||
    $route == 'user.register'
  ) {
    $path = str_replace('.', '_', $route);

    $suggestions[] = 'page_title__user';
    $suggestions[] = 'page_title__' . $path;
  }
}

/**
 * Form_alter()
 */
function gin_login_form_alter(&$form, $form_state, $form_id) {
  // User form (Login, Register or Forgot password)
  if (strpos($form_id, 'user_login') !== FALSE || strpos($form_id, 'user_register') !== FALSE || strpos($form_id, 'user_pass') !== FALSE) {
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
  }

  // Adding button/links to Register and Forgot password.
  if (strpos($form_id, 'user_login') !== FALSE) {
    // Move actions before new elements.
    $form['actions']['#weight'] = '98';

    // Add new class to submit button.
    $form['actions']['submit']['#attributes']['class'][] = 'button-login';

    // New wrapper.
    $form['more-links'] = [
      '#type' => 'container',
      '#weight' => '99',
      '#attributes' => ['class' => ['more-links']],
    ];

    // Register button.
    if (\Drupal::config('user.settings')->get('register') != UserInterface::REGISTER_ADMINISTRATORS_ONLY) {
      $form['more-links']['register_button'] = [
        '#type' => 'link',
        '#url' => Url::fromRoute('user.register'),
        '#title' => t('Create new account'),
        '#attributes' => [
          'class' => [
            'register-button',
            'button',
            'button--secondary',
          ],
        ],
        '#weight' => '1',
      ];
    }

    // Forgot password link.
    $form['more-links']['forgot_password_link'] = [
      '#type' => 'link',
      '#url' => Url::fromRoute('user.pass'),
      '#title' => t('Forgot your password?'),
      '#attributes' => ['class' => ['link', 'forgot-password-link']],
      '#weight' => '2',
    ];
  }

  // Changing name of Reset button.
  if (strpos($form_id, 'user_pass') !== FALSE) {
    $form['actions']['submit']['#value'] = t('Reset');
  }
}

/**
 * Theme()
 */
function gin_login_theme() {
  // Page.
  $theme['page__user__login'] = [
    'template' => 'page/page--user--login',
  ];
  $theme['page__user__password'] = [
    'template' => 'page/page--user--password',
  ];
  $theme['page__user__register'] = [
    'template' => 'page/page--user--register',
  ];

  // Title.
  $theme['page_title__user_login'] = [
    'template' => 'content/page-title--user-login',
  ];
  $theme['page_title__user_pass'] = [
    'template' => 'content/page-title--user-pass',
  ];
  $theme['page_title__user_register'] = [
    'template' => 'content/page-title--user-register',
  ];

  return $theme;
}

/**
 * CSS_alter()
 */
function gin_login_css_alter(&$css, $assets) {
  // UPDATE THIS PATH TO YOUR MODULE'S CSS PATH.
  $path = drupal_get_path('module', 'gin_login') . '/dist/css/gin_login.css';
  if (isset($css[$path])) {
    // Use anything greater than 100 to have it load
    // after the theme as CSS_AGGREGATE_THEME is set to 100.
    $css[$path]['group'] = 200;
  }
}

/**
 * Increases or decreases the brightness of a color.
 */
function _gin_login_adjust_brightness($hexCode, $adjustPercent) {
  $hexCode = ltrim($hexCode, '#');

  if (strlen($hexCode) == 3) {
    $hexCode = $hexCode[0] . $hexCode[0] . $hexCode[1] . $hexCode[1] . $hexCode[2] . $hexCode[2];
  }

  $hexCode = array_map('hexdec', str_split($hexCode, 2));

  foreach ($hexCode as & $color) {
    $adjustableLimit = $adjustPercent < 0 ? $color : 255 - $color;
    $adjustAmount = ceil($adjustableLimit * $adjustPercent);

    $color = str_pad(dechex($color + $adjustAmount), 2, '0', STR_PAD_LEFT);
  }

  return '#' . implode($hexCode);
}
